name: starruler2
version: '2.0'
icon: snap/gui/sr2.png
summary: A massive scale 4X/RTS set in space
description: >
  Explore dozens, hundreds, or even thousands of systems in a galaxy of your
  choosing, expand across its planets, exploit the resources you find, and
  ultimately exterminate any who stand in your way. The fate of your empire
  depends on your ability to master the economy, field a military, influence
  galactic politics, and learn what you can about the universe.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  # - build-on: arm64

# passthrough:
#   layout:
#     /starruler2:
#       bind: $SNAP/starruler2
#     /starruler2/mods:
#       bind: $SNAP_USER_COMMON/mods
#     /starruler2/music:
#       bind: $SNAP_USER_COMMON/music

parts:
  # ensure-moddable:
  #   plugin: nil
  #   override-pull: |
  #     cat <<EOF > ensure-moddable
  #     #!/bin/sh
  #     needs_update=true

  #     . \$SNAP_USER_DATA/.last_mods_revision 2>/dev/null || true
  #     if [ "\$SNAP_DESKTOP_LAST_REVISION" = "\$SNAP_REVISION" ]; then
  #       needs_update=false
  #     fi

  #     if [ \$needs_update = true ]; then
  #       mkdir -p "\$SNAPCRAFT_COMMON/mods" "\$SNAPCRAFT_COMMON/music"
  #       rsync -rv "\$SNAP/starruler2/mods.real/" "\$SNAPCRAFT_COMMON/mods/"
  #     fi

  #     [ \$needs_update = true ] && echo "SNAP_DESKTOP_LAST_REVISION=\$SNAP_REVISION" > \$SNAP_USER_DATA/.last_mods_revision

  #     exec "\$@"
  #     EOF
  #   override-build: |
  #     install -m755 -D -t "$SNAPCRAFT_PART_INSTALL/bin" ensure-moddable

  starruler2:
    plugin: make
    source: https://github.com/OpenSRProject/OpenStarRuler.git
    source-branch: v1.0.0
    source-depth: 1
    # override-pull: |
    #   snapcraftctl pull
    #   patch -Np1 -i "$SNAPCRAFT_PROJECT_DIR/patches/arm-support.patch"
    #   patch -Np1 -i "$SNAPCRAFT_PROJECT_DIR/patches/os-asm.patch"
    override-build: |
      make -j"$SNAPCRAFT_PARALLEL_BUILD_COUNT" -f source/linux/Makefile compile

      install -D -t "$SNAPCRAFT_PART_INSTALL"/starruler2/ \
        StarRuler2.sh \
        COPYING \
        credits.txt

      for i in bin/lin*; do
        install -D -t "$SNAPCRAFT_PART_INSTALL/starruler2/$i" "$i/StarRuler2.bin"
      done
    stage:
    - -starruler2/bin/win64
    build-environment:
    - CPATH: /snap/gnome-42-2204-sdk/current/usr/include:/snap/gnome-42-2204-sdk/current/usr/include/freetype2:/snap/gnome-42-2204-sdk/current/usr/include/libpng
    - LIBRARY_PATH: /usr/lib/gcc/x86_64-linux-gnu/11:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/lib:/snap/core22/current/usr/lib:/snap/core22/current/lib
    build-snaps:
    - cmake
    build-packages:
    - libbz2-dev
    - libcurl4-openssl-dev
    - libglew-dev
    - libglu1-mesa-dev
    - libogg-dev
    - libopenal-dev
    - libstdc++-11-dev
    - libvorbis-dev
    - libxi-dev
    - libxrandr-dev
    - libxxf86vm-dev
    stage-packages:
    - libcurl4
    - libglew2.2
    - libglu1-mesa
    - libogg0
    - libopenal1
    - libvorbis0a
    - libvorbisfile3

  starruler2-data:
    after: [starruler2]
    plugin: dump
    source: https://github.com/OpenSRProject/OpenStarRuler-Data/archive/refs/tags/v1.0.0.tar.gz
    stage:
      - starruler2
    organize:
      data: starruler2/data
      locales: starruler2/locales
      maps: starruler2/maps
      mods: starruler2/mods
      scripts: starruler2/scripts

apps:
  starruler2:
    command: starruler2/StarRuler2.sh
    extensions: [gnome]
    plugs:
    - audio-playback
    - network
    - opengl
